
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnPV_vYY91x_tZC12vIVb9URQvoE48Y0w',
    appId: '1:610302298484:android:db85f271038e1477fd0421',
    messagingSenderId: '610302298484',
    projectId: 'nbig-app',
    storageBucket: 'nbig-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1sTw60c8NWOXkVQ1JmrWOjwxFSmSBSE',
    appId: '1:610302298484:ios:ce2754df20aa9490fd0421',
    messagingSenderId: '610302298484',
    projectId: 'nbig-app',
    storageBucket: 'nbig-app.firebasestorage.app',
    androidClientId:
        '610302298484-k65jadtq80ptt0202ho4h19ibb1ib8rv.apps.googleusercontent.com',
    iosBundleId: 'com.nbig.doctorApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzndqFIozKgt5whaWRdy1IaI_z2lFrTwg',
    appId: '1:610302298484:web:f77e47d11773ddadfd0421',
    messagingSenderId: '610302298484',
    projectId: 'nbig-app',
    authDomain: 'nbig-app.firebaseapp.com',
    storageBucket: 'nbig-app.firebasestorage.app',
    measurementId: 'G-WFKWZ9ENFC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV1sTw60c8NWOXkVQ1JmrWOjwxFSmSBSE',
    appId: '1:610302298484:ios:42b13eac01494186fd0421',
    messagingSenderId: '610302298484',
    projectId: 'nbig-app',
    storageBucket: 'nbig-app.firebasestorage.app',
    androidClientId:
        '610302298484-k65jadtq80ptt0202ho4h19ibb1ib8rv.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzndqFIozKgt5whaWRdy1IaI_z2lFrTwg',
    appId: '1:610302298484:web:9cf8395bc0407121fd0421',
    messagingSenderId: '610302298484',
    projectId: 'nbig-app',
    authDomain: 'nbig-app.firebaseapp.com',
    storageBucket: 'nbig-app.firebasestorage.app',
    measurementId: 'G-T9YLZ63M91',
  );
}
